# Generated by Django 5.1 on 2024-08-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_ingredients_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='menu_time',
            new_name='menu_item',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='pricePerUnit',
            new_name='price',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='units',
            field=models.CharField(default='unit', max_length=200),
        ),
    ]
