# Generated by Django 5.1 on 2024-08-17 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_menu_time_expense_menu_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='pricePerUnit',
            new_name='price',
        ),
    ]
