# Generated by Django 5.1 on 2024-08-17 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_priceperunit_menuitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='price',
            new_name='pricePerUnit',
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.menuitem')),
            ],
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
